# Generated by Django 5.0.6 on 2024-06-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='code',
        ),
    ]
