# Generated by Django 5.0.6 on 2024-06-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=200000, max_digits=12),
            preserve_default=False,
        ),
    ]
