# Generated by Django 5.0.6 on 2024-06-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Office',
            new_name='Contructor',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='office',
            new_name='contructor',
        ),
    ]
