# Generated by Django 5.0.6 on 2024-06-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_office_contructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contructor',
            name='contructor_attachments',
            field=models.FileField(blank=True, null=True, upload_to='media/projects/attachments'),
        ),
        migrations.AddField(
            model_name='contructor',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
